spring.application.name=smart-campus-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_campus
spring.datasource.username=postgres
spring.datasource.password=Nanga01
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8081

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB



#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

spring.web.resources.add-mappings=true

# Static Resources
spring.web.resources.static-locations=classpath:/static/,file:./uploads/

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


spring.security.oauth2.client.registration.google.scope=email,profile

# JWT
app.jwt.secret=this-is-a-very-long-secret-key-for-smart-campus-app-2026-replace-this
app.jwt.expiration=86400000

# Frontend URL
app.frontend.url=http://localhost:5174
